package `in`.sanskar.rpsarena.ui

import `in`.sanskar.rpsarena.model.AppLanguage
import `in`.sanskar.rpsarena.model.Difficulty
import `in`.sanskar.rpsarena.model.Gesture
import `in`.sanskar.rpsarena.model.MatchMode

data class ArenaStrings(
    val appName: String,
    val settings: String,
    val back: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val enterArena: String,
    val chooseArena: String,
    val offlineTagline: String,
    val play: String,
    val stats: String,
    val history: String,
    val achievements: String,
    val about: String,
    val madeBy: String,
    val opponent: String,
    val cpu: String,
    val twoPlayer: String,
    val rules: String,
    val classic: String,
    val lizardSpock: String,
    val difficulty: String,
    val mode: String,
    val timer: String,
    val timerOff: String,
    val seed: String,
    val seedReplayHint: String,
    val applySeed: String,
    val chooseGesture: String,
    val lastRound: String,
    val newMatch: String,
    val noHistory: String,
    val rounds: String,
    val wins: String,
    val losses: String,
    val draws: String,
    val winRate: String,
    val bestStreak: String,
    val recentTrend: String,
    val appearance: String,
    val accessibility: String,
    val accessibilityNote: String,
    val dataPrivacy: String,
    val followSystemTheme: String,
    val darkTheme: String,
    val reducedMotion: String,
    val sound: String,
    val haptics: String,
    val playerName: String,
    val savePlayerName: String,
    val language: String,
    val english: String,
    val hindi: String,
    val exportBackup: String,
    val importBackup: String,
    val backupHint: String,
    val resetLocalData: String,
    val resetWarning: String,
    val cancel: String,
    val confirmReset: String,
    val aboutBody: String,
    val extendedRules: String,
    val cpuTransparency: String,
    val version: String,
    val license: String,
    val localTurnOne: String,
    val localTurnTwo: String,
    val timerRemaining: String,
    val playerOneTimeout: String,
    val playerTwoTimeout: String,
    val playerOneWinsRound: String,
    val playerTwoWinsRound: String,
    val roundDraw: String,
    val backupReady: String,
    val localDataReset: String,
    val backupImportedPrefix: String,
    val historyRecords: String,
    val invalidBackupHeader: String,
    val backupTooLarge: String,
    val backupTooManyRecords: String,
    val malformedBackupRecord: String,
    val invalidSettingsRecord: String,
    val invalidStatsRecord: String,
    val backupMissingSettings: String,
    val backupMissingStats: String,
    val duplicateSettingsRecord: String,
    val duplicateStatsRecord: String,
    val unknownBackupRecord: String,
    private val gestureLabels: Map<Gesture, String>,
    private val difficultyLabels: Map<Difficulty, String>,
    private val modeLabels: Map<MatchMode, String>,
) {
    fun gestureLabel(gesture: Gesture): String = gestureLabels.getValue(gesture)
    fun difficultyLabel(difficulty: Difficulty): String = difficultyLabels.getValue(difficulty)
    fun modeLabel(mode: MatchMode): String = modeLabels.getValue(mode)
}

fun stringsFor(language: AppLanguage): ArenaStrings = when (language) {
    AppLanguage.ENGLISH -> ArenaStrings(
        appName = "RPS Arena",
        settings = "Settings",
        back = "← Back",
        welcomeTitle = "Welcome to RPS Arena",
        welcomeBody = "Fast, offline-first matches with transparent CPU difficulty and an optional Lizard–Spock ruleset.",
        enterArena = "Enter the Arena",
        chooseArena = "Choose your arena",
        offlineTagline = "Classic strategy. No account. No network required.",
        play = "Play",
        stats = "Stats",
        history = "History",
        achievements = "Achievements",
        about = "About",
        madeBy = "Made by the Sanskar",
        opponent = "Opponent",
        cpu = "CPU",
        twoPlayer = "2 Player",
        rules = "Rules",
        classic = "Classic",
        lizardSpock = "Lizard–Spock",
        difficulty = "Difficulty",
        mode = "Mode",
        timer = "Round timer",
        timerOff = "Off",
        seed = "Challenge seed",
        seedReplayHint = "Same seed + same moves = replayable CPU challenge",
        applySeed = "Apply seed",
        chooseGesture = "Choose a gesture",
        lastRound = "Last round",
        newMatch = "New match",
        noHistory = "No rounds yet. Your latest 30 rounds stay on this device.",
        rounds = "Rounds",
        wins = "Wins",
        losses = "Losses",
        draws = "Draws",
        winRate = "Win rate",
        bestStreak = "Best streak",
        recentTrend = "Recent 10-round trend",
        appearance = "Appearance",
        accessibility = "Accessibility",
        accessibilityNote = "Core actions use text labels, large touch targets, visible status feedback, and keyboard-friendly controls.",
        dataPrivacy = "Data & privacy",
        followSystemTheme = "Follow system theme",
        darkTheme = "Dark theme",
        reducedMotion = "Reduced motion",
        sound = "Sound",
        haptics = "Haptics",
        playerName = "Local player name",
        savePlayerName = "Save player name",
        language = "Language",
        english = "English",
        hindi = "Hindi",
        exportBackup = "Prepare backup",
        importBackup = "Import backup",
        backupHint = "Paste or copy the versioned backup text here. It contains local settings, stats, and recent history.",
        resetLocalData = "Reset local data",
        resetWarning = "This removes local stats, history, and preferences from this device.",
        cancel = "Cancel",
        confirmReset = "Confirm reset",
        aboutBody = "An open-source, offline-first Rock Paper Scissors game for Android and desktop.",
        extendedRules = "Optional extended rules: Rock–Paper–Scissors–Lizard–Spock.",
        cpuTransparency = "CPU modes are local and deterministic from a seed; no hidden online model is used.",
        version = "Version",
        license = "License",
        localTurnOne = "Player 1: choose secretly",
        localTurnTwo = "Player 2: choose now — Player 1 move is hidden",
        timerRemaining = "Time remaining",
        playerOneTimeout = "Player 1 timed out",
        playerTwoTimeout = "Player 2 timed out",
        playerOneWinsRound = "Player 1 wins the round",
        playerTwoWinsRound = "Player 2 wins the round",
        roundDraw = "Draw",
        backupReady = "Backup text is ready to copy and save securely.",
        localDataReset = "Local statistics, history, and preferences were reset.",
        backupImportedPrefix = "Imported settings, statistics, and",
        historyRecords = "history records",
        invalidBackupHeader = "Unsupported or missing backup header",
        backupTooLarge = "Backup is too large",
        backupTooManyRecords = "Backup contains too many records",
        malformedBackupRecord = "Malformed backup record",
        invalidSettingsRecord = "Invalid settings record",
        invalidStatsRecord = "Invalid stats record",
        backupMissingSettings = "Backup has no settings record",
        backupMissingStats = "Backup has no stats record",
        duplicateSettingsRecord = "Duplicate settings record",
        duplicateStatsRecord = "Duplicate stats record",
        unknownBackupRecord = "Unknown backup record",
        gestureLabels = mapOf(
            Gesture.ROCK to "Rock",
            Gesture.PAPER to "Paper",
            Gesture.SCISSORS to "Scissors",
            Gesture.LIZARD to "Lizard",
            Gesture.SPOCK to "Spock",
        ),
        difficultyLabels = mapOf(
            Difficulty.EASY to "Easy",
            Difficulty.NORMAL to "Normal",
            Difficulty.EXPERT to "Expert",
        ),
        modeLabels = mapOf(
            MatchMode.BEST_OF_3 to "Best of 3",
            MatchMode.BEST_OF_5 to "Best of 5",
            MatchMode.ENDLESS to "Endless",
            MatchMode.STREAK to "Streak",
            MatchMode.TOURNAMENT to "Tournament",
        ),
    )
    AppLanguage.HINDI -> ArenaStrings(
        appName = "RPS Arena",
        settings = "सेटिंग्स",
        back = "← वापस",
        welcomeTitle = "RPS Arena में आपका स्वागत है",
        welcomeBody = "पारदर्शी CPU कठिनाई और वैकल्पिक Lizard–Spock नियमों के साथ तेज़, ऑफ़लाइन मैच।",
        enterArena = "एरीना में जाएँ",
        chooseArena = "अपना एरीना चुनें",
        offlineTagline = "क्लासिक रणनीति। कोई अकाउंट नहीं। नेटवर्क की जरूरत नहीं।",
        play = "खेलें",
        stats = "आँकड़े",
        history = "इतिहास",
        achievements = "उपलब्धियाँ",
        about = "परिचय",
        madeBy = "Made by the Sanskar",
        opponent = "प्रतिद्वंद्वी",
        cpu = "CPU",
        twoPlayer = "2 खिलाड़ी",
        rules = "नियम",
        classic = "क्लासिक",
        lizardSpock = "Lizard–Spock",
        difficulty = "कठिनाई",
        mode = "मोड",
        timer = "राउंड टाइमर",
        timerOff = "बंद",
        seed = "चैलेंज सीड",
        seedReplayHint = "एक ही seed + एक जैसी चालें = दोहराने योग्य CPU चुनौती",
        applySeed = "सीड लागू करें",
        chooseGesture = "एक चाल चुनें",
        lastRound = "पिछला राउंड",
        newMatch = "नया मैच",
        noHistory = "अभी कोई राउंड नहीं। आपके नवीनतम 30 राउंड इसी डिवाइस पर रहते हैं।",
        rounds = "राउंड",
        wins = "जीत",
        losses = "हार",
        draws = "ड्रॉ",
        winRate = "जीत दर",
        bestStreak = "सर्वश्रेष्ठ स्ट्रीक",
        recentTrend = "हाल के 10 राउंड का ट्रेंड",
        appearance = "दिखावट",
        accessibility = "एक्सेसिबिलिटी",
        accessibilityNote = "मुख्य क्रियाओं में टेक्स्ट लेबल, बड़े टच टार्गेट, स्पष्ट स्थिति प्रतिक्रिया और कीबोर्ड-अनुकूल नियंत्रण हैं।",
        dataPrivacy = "डेटा और प्राइवेसी",
        followSystemTheme = "सिस्टम थीम अपनाएँ",
        darkTheme = "डार्क थीम",
        reducedMotion = "कम एनीमेशन",
        sound = "ध्वनि",
        haptics = "हैप्टिक्स",
        playerName = "स्थानीय खिलाड़ी का नाम",
        savePlayerName = "खिलाड़ी का नाम सहेजें",
        language = "भाषा",
        english = "English",
        hindi = "हिन्दी",
        exportBackup = "बैकअप तैयार करें",
        importBackup = "बैकअप आयात करें",
        backupHint = "यहाँ वर्ज़न वाला बैकअप टेक्स्ट पेस्ट या कॉपी करें। इसमें स्थानीय सेटिंग्स, आँकड़े और हाल का इतिहास होता है।",
        resetLocalData = "स्थानीय डेटा रीसेट करें",
        resetWarning = "यह इस डिवाइस से स्थानीय आँकड़े, इतिहास और पसंद हटाता है।",
        cancel = "रद्द करें",
        confirmReset = "रीसेट की पुष्टि करें",
        aboutBody = "Android और desktop के लिए एक open-source, offline-first Rock Paper Scissors गेम।",
        extendedRules = "वैकल्पिक विस्तारित नियम: Rock–Paper–Scissors–Lizard–Spock।",
        cpuTransparency = "CPU मोड स्थानीय हैं और seed से deterministic हैं; कोई छिपा online model उपयोग नहीं होता।",
        version = "वर्ज़न",
        license = "लाइसेंस",
        localTurnOne = "खिलाड़ी 1: अपनी चाल गुप्त रूप से चुनें",
        localTurnTwo = "खिलाड़ी 2: अब चुनें — खिलाड़ी 1 की चाल छिपी है",
        timerRemaining = "बाकी समय",
        playerOneTimeout = "खिलाड़ी 1 का समय समाप्त हुआ",
        playerTwoTimeout = "खिलाड़ी 2 का समय समाप्त हुआ",
        playerOneWinsRound = "खिलाड़ी 1 ने राउंड जीता",
        playerTwoWinsRound = "खिलाड़ी 2 ने राउंड जीता",
        roundDraw = "ड्रॉ",
        backupReady = "बैकअप टेक्स्ट कॉपी करके सुरक्षित रखने के लिए तैयार है।",
        localDataReset = "स्थानीय आँकड़े, इतिहास और पसंद रीसेट कर दिए गए।",
        backupImportedPrefix = "सेटिंग्स, आँकड़े और आयात किए गए",
        historyRecords = "इतिहास रिकॉर्ड",
        invalidBackupHeader = "बैकअप हेडर समर्थित नहीं है या मौजूद नहीं है",
        backupTooLarge = "बैकअप बहुत बड़ा है",
        backupTooManyRecords = "बैकअप में बहुत अधिक रिकॉर्ड हैं",
        malformedBackupRecord = "बैकअप रिकॉर्ड का प्रारूप गलत है",
        invalidSettingsRecord = "सेटिंग्स रिकॉर्ड अमान्य है",
        invalidStatsRecord = "आँकड़े रिकॉर्ड अमान्य है",
        backupMissingSettings = "बैकअप में सेटिंग्स रिकॉर्ड नहीं है",
        backupMissingStats = "बैकअप में आँकड़े रिकॉर्ड नहीं है",
        duplicateSettingsRecord = "सेटिंग्स रिकॉर्ड दोहराया गया है",
        duplicateStatsRecord = "आँकड़े रिकॉर्ड दोहराया गया है",
        unknownBackupRecord = "अज्ञात बैकअप रिकॉर्ड",
        gestureLabels = mapOf(
            Gesture.ROCK to "पत्थर",
            Gesture.PAPER to "कागज़",
            Gesture.SCISSORS to "कैंची",
            Gesture.LIZARD to "छिपकली",
            Gesture.SPOCK to "स्पॉक",
        ),
        difficultyLabels = mapOf(
            Difficulty.EASY to "आसान",
            Difficulty.NORMAL to "सामान्य",
            Difficulty.EXPERT to "विशेषज्ञ",
        ),
        modeLabels = mapOf(
            MatchMode.BEST_OF_3 to "3 में सर्वश्रेष्ठ",
            MatchMode.BEST_OF_5 to "5 में सर्वश्रेष्ठ",
            MatchMode.ENDLESS to "अंतहीन",
            MatchMode.STREAK to "स्ट्रीक",
            MatchMode.TOURNAMENT to "टूर्नामेंट",
        ),
    )
}
