package `in`.sanskar.rpsarena.ui

import `in`.sanskar.rpsarena.model.AppLanguage

data class ArenaStrings(
    val appName: String,
    val settings: String,
    val back: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val enterArena: String,
    val chooseArena: String,
    val offlineTagline: String,
    val play: String,
    val stats: String,
    val history: String,
    val achievements: String,
    val about: String,
    val madeBy: String,
    val opponent: String,
    val cpu: String,
    val twoPlayer: String,
    val rules: String,
    val classic: String,
    val lizardSpock: String,
    val difficulty: String,
    val mode: String,
    val timer: String,
    val timerOff: String,
    val seed: String,
    val chooseGesture: String,
    val lastRound: String,
    val newMatch: String,
    val noHistory: String,
    val rounds: String,
    val wins: String,
    val losses: String,
    val draws: String,
    val winRate: String,
    val bestStreak: String,
    val recentTrend: String,
    val appearance: String,
    val accessibility: String,
    val dataPrivacy: String,
    val followSystemTheme: String,
    val darkTheme: String,
    val reducedMotion: String,
    val sound: String,
    val haptics: String,
    val playerName: String,
    val language: String,
    val english: String,
    val hindi: String,
    val exportBackup: String,
    val importBackup: String,
    val backupHint: String,
    val resetLocalData: String,
    val aboutBody: String,
    val cpuTransparency: String,
    val localTurnOne: String,
    val localTurnTwo: String,
    val timerRemaining: String,
)

fun stringsFor(language: AppLanguage): ArenaStrings = when (language) {
    AppLanguage.ENGLISH -> ArenaStrings(
        appName = "RPS Arena",
        settings = "Settings",
        back = "← Back",
        welcomeTitle = "Welcome to RPS Arena",
        welcomeBody = "Fast, offline-first matches with transparent CPU difficulty and an optional Lizard–Spock ruleset.",
        enterArena = "Enter the Arena",
        chooseArena = "Choose your arena",
        offlineTagline = "Classic strategy. No account. No network required.",
        play = "Play",
        stats = "Stats",
        history = "History",
        achievements = "Achievements",
        about = "About",
        madeBy = "Made by the Sanskar",
        opponent = "Opponent",
        cpu = "CPU",
        twoPlayer = "2 Player",
        rules = "Rules",
        classic = "Classic",
        lizardSpock = "Lizard–Spock",
        difficulty = "Difficulty",
        mode = "Mode",
        timer = "Round timer",
        timerOff = "Off",
        seed = "Challenge seed",
        chooseGesture = "Choose a gesture",
        lastRound = "Last round",
        newMatch = "New match",
        noHistory = "No rounds yet. Your latest 30 rounds stay on this device.",
        rounds = "Rounds",
        wins = "Wins",
        losses = "Losses",
        draws = "Draws",
        winRate = "Win rate",
        bestStreak = "Best streak",
        recentTrend = "Recent 10-round trend",
        appearance = "Appearance",
        accessibility = "Accessibility",
        dataPrivacy = "Data & privacy",
        followSystemTheme = "Follow system theme",
        darkTheme = "Dark theme",
        reducedMotion = "Reduced motion",
        sound = "Sound",
        haptics = "Haptics",
        playerName = "Local player name",
        language = "Language",
        english = "English",
        hindi = "Hindi",
        exportBackup = "Prepare backup",
        importBackup = "Import backup",
        backupHint = "Paste or copy the versioned backup text here. It contains local settings, stats, and recent history.",
        resetLocalData = "Reset local data",
        aboutBody = "An open-source, offline-first Rock Paper Scissors game for Android and desktop.",
        cpuTransparency = "CPU modes are local and deterministic from a seed; no hidden online model is used.",
        localTurnOne = "Player 1: choose secretly",
        localTurnTwo = "Player 2: choose now — Player 1 move is hidden",
        timerRemaining = "Time remaining",
    )
    AppLanguage.HINDI -> ArenaStrings(
        appName = "RPS Arena",
        settings = "सेटिंग्स",
        back = "← वापस",
        welcomeTitle = "RPS Arena में आपका स्वागत है",
        welcomeBody = "पारदर्शी CPU कठिनाई और वैकल्पिक Lizard–Spock नियमों के साथ तेज़, ऑफ़लाइन मैच।",
        enterArena = "एरीना में जाएँ",
        chooseArena = "अपना एरीना चुनें",
        offlineTagline = "क्लासिक रणनीति। कोई अकाउंट नहीं। नेटवर्क की जरूरत नहीं।",
        play = "खेलें",
        stats = "आँकड़े",
        history = "इतिहास",
        achievements = "उपलब्धियाँ",
        about = "परिचय",
        madeBy = "Made by the Sanskar",
        opponent = "प्रतिद्वंद्वी",
        cpu = "CPU",
        twoPlayer = "2 खिलाड़ी",
        rules = "नियम",
        classic = "क्लासिक",
        lizardSpock = "Lizard–Spock",
        difficulty = "कठिनाई",
        mode = "मोड",
        timer = "राउंड टाइमर",
        timerOff = "बंद",
        seed = "चैलेंज सीड",
        chooseGesture = "एक चाल चुनें",
        lastRound = "पिछला राउंड",
        newMatch = "नया मैच",
        noHistory = "अभी कोई राउंड नहीं। आपके नवीनतम 30 राउंड इसी डिवाइस पर रहते हैं।",
        rounds = "राउंड",
        wins = "जीत",
        losses = "हार",
        draws = "ड्रॉ",
        winRate = "जीत दर",
        bestStreak = "सर्वश्रेष्ठ स्ट्रीक",
        recentTrend = "हाल के 10 राउंड का ट्रेंड",
        appearance = "दिखावट",
        accessibility = "एक्सेसिबिलिटी",
        dataPrivacy = "डेटा और प्राइवेसी",
        followSystemTheme = "सिस्टम थीम अपनाएँ",
        darkTheme = "डार्क थीम",
        reducedMotion = "कम एनीमेशन",
        sound = "ध्वनि",
        haptics = "हैप्टिक्स",
        playerName = "स्थानीय खिलाड़ी का नाम",
        language = "भाषा",
        english = "English",
        hindi = "हिन्दी",
        exportBackup = "बैकअप तैयार करें",
        importBackup = "बैकअप आयात करें",
        backupHint = "यहाँ वर्ज़न वाला बैकअप टेक्स्ट पेस्ट या कॉपी करें। इसमें स्थानीय सेटिंग्स, आँकड़े और हाल का इतिहास होता है।",
        resetLocalData = "स्थानीय डेटा रीसेट करें",
        aboutBody = "Android और desktop के लिए एक open-source, offline-first Rock Paper Scissors गेम।",
        cpuTransparency = "CPU मोड स्थानीय हैं और seed से deterministic हैं; कोई छिपा online model उपयोग नहीं होता।",
        localTurnOne = "खिलाड़ी 1: अपनी चाल गुप्त रूप से चुनें",
        localTurnTwo = "खिलाड़ी 2: अब चुनें — खिलाड़ी 1 की चाल छिपी है",
        timerRemaining = "बाकी समय",
    )
}
