changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Security and reliability
      labels:
        - security
        - reliability
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
